meta_product_name: "Handpicked Lodges"
meta_title: "Handpicked Lodges - Highland Holiday Homes in Aviemore and the Cairngorms"
meta_description: "Book your luxury Cairngorms lodge direct - Pet friendly, woodburner, sauna, hot tub, all in and around Aviemore"
meta_image: "temp-og-image.jpg"                       # should exist in `app/assets/images/`
