meta_product_name: "Seasgair"
meta_title: "Seasgair - Highland Holiday Homes in Aviemore and Cairngorms"
meta_description: "Seasgair - a stunning collection of luxury self catering holiday homes in the Cairngorms - Pet friendly, woodburner, hot tub, sauna, cinema - around Aviemore"
meta_image: "banner-1.jpg"                       # should exist in `app/assets/images/`
